export const navLinks = [
  { label: "Science", href: "#science" },
  { label: "Platform", href: "#platform" },
  { label: "Capabilities", href: "#capabilities" },
  { label: "Research", href: "#research" },
  { label: "About", href: "#about" },
];

export const sciencePillars = [
  {
    id: "01",
    title: "Molecular Intelligence",
    subtitle: "Decoding biological mechanisms at molecular resolution",
    description:
      "We profile biological systems at single-molecule sensitivity, mapping protein interactions, metabolic pathways, and signaling cascades that drive cellular behavior. Our molecular intelligence platform identifies therapeutic targets hidden within the complexity of living systems.",
    tags: ["Proteomics", "Pathway Analysis", "Target ID"],
  },
  {
    id: "02",
    title: "Spatial Biology",
    subtitle: "Mapping biological activity across cells and tissues",
    description:
      "Biological function is shaped by spatial context. We develop and apply multiplexed imaging and spatial transcriptomics to understand how cells organize, communicate, and dysfunction within their native tissue architecture.",
    tags: ["Spatial Transcriptomics", "Multiplexed Imaging", "Tissue Architecture"],
  },
  {
    id: "03",
    title: "Computational Discovery",
    subtitle: "Finding patterns inside complex biological datasets",
    description:
      "We build machine learning models trained on high-dimensional biological data to identify patterns invisible to conventional analysis. Our computational pipelines transform raw measurements into actionable biological insight.",
    tags: ["Machine Learning", "Dimensionality Reduction", "Network Biology"],
  },
  {
    id: "04",
    title: "Precision Therapeutics",
    subtitle: "Translating insight into targeted therapeutic strategies",
    description:
      "Every discovery is evaluated for therapeutic relevance. We bridge the gap between biological understanding and clinical application, designing targeted interventions informed by molecular evidence and validated through rigorous experimental models.",
    tags: ["Drug Design", "Biomarker Strategy", "Translational Research"],
  },
];

export const platformStages = [
  {
    id: "01",
    title: "Observe",
    description: "High-resolution imaging and multiplexed profiling capture biological systems in their native state.",
    detail: "Advanced microscopy and spatial profiling technologies generate comprehensive views of cellular and molecular activity across tissues.",
    metric: "10⁶",
    metricLabel: "measurements per sample",
  },
  {
    id: "02",
    title: "Decode",
    description: "Molecular profiling extracts meaningful signals from complex biological measurements.",
    detail: "Proprietary assays and computational pipelines deconvolve layered biological data into interpretable molecular signatures.",
    metric: "4.2K",
    metricLabel: "molecular features per run",
  },
  {
    id: "03",
    title: "Model",
    description: "Machine learning models identify patterns and predict biological behavior.",
    detail: "Graph neural networks and generative models learn the rules governing biological systems, enabling prediction of cellular responses and pathway dynamics.",
    metric: "93%",
    metricLabel: "prediction accuracy",
  },
  {
    id: "04",
    title: "Validate",
    description: "Experimental systems confirm computational predictions with biological evidence.",
    detail: "Organoid models, CRISPR screens, and functional assays test hypotheses generated by the computational pipeline in biologically relevant contexts.",
    metric: "27",
    metricLabel: "validation models",
  },
  {
    id: "05",
    title: "Discover",
    description: "Integrated insight drives therapeutic hypothesis generation.",
    detail: "The convergence of observation, decoding, modeling, and validation produces novel therapeutic targets, biomarker signatures, and mechanistic understanding.",
    metric: "12",
    metricLabel: "active programs",
  },
];

export const capabilities = [
  {
    title: "Advanced Microscopy",
    description: "Sub-cellular resolution imaging across multiple modalities — confocal, lightsheet, electron, and super-resolution — revealing biological structure at every scale.",
    tags: ["Confocal", "Lightsheet", "Super-Resolution", "EM"],
  },
  {
    title: "Spatial Transcriptomics",
    description: "Gene expression mapping within intact tissue sections, preserving spatial context while profiling thousands of transcripts simultaneously.",
    tags: ["MERFISH", "Visium", "Stereo-seq", "In Situ"],
  },
  {
    title: "Molecular Profiling",
    description: "Multi-omic characterization of biological samples — proteomics, metabolomics, epigenomics — generating comprehensive molecular snapshots.",
    tags: ["Proteomics", "Metabolomics", "Epigenomics", "Multi-omic"],
  },
  {
    title: "Computational Biology",
    description: "Scalable analysis pipelines and custom algorithms for high-dimensional biological data, from raw signal processing to network-level interpretation.",
    tags: ["Pipeline Dev", "Network Analysis", "Dimensionality Reduction"],
  },
  {
    title: "AI-Assisted Discovery",
    description: "Deep learning models trained on biological data to predict molecular interactions, classify cell states, and identify therapeutic opportunities.",
    tags: ["Deep Learning", "Graph Networks", "Generative Models"],
  },
  {
    title: "Therapeutic Validation",
    description: "Rigorous experimental validation using organoid systems, CRISPR screens, and disease-relevant models to confirm biological hypotheses.",
    tags: ["Organoids", "CRISPR", "Functional Assays", "Phenotypic Screening"],
  },
];

export const researchPrograms = [
  {
    id: "NXP-001",
    title: "Precision Oncology",
    description: "Mapping tumor microenvironments at single-cell resolution to identify context-dependent therapeutic vulnerabilities. Our spatial profiling approach reveals how immune-stromal-tumor interactions shape treatment response.",
    status: "Active",
    focus: "Tumor Microenvironment",
    tags: ["Spatial Biology", "Immuno-Oncology", "Single-Cell"],
    year: "2024 — Present",
  },
  {
    id: "NXP-002",
    title: "Neurodegenerative Biology",
    description: "Characterizing the spatial and molecular patterns associated with neuronal decline. We combine proteomic profiling with advanced imaging to understand protein aggregation cascades and their propagation through neural circuits.",
    status: "Active",
    focus: "Protein Misfolding",
    tags: ["Proteomics", "Neuroimaging", "Protein Biology"],
    year: "2023 — Present",
  },
  {
    id: "NXP-003",
    title: "Targeted Delivery Systems",
    description: "Studying how therapeutic payloads navigate biological barriers to reach their intended targets. Our computational models predict tissue penetration and cellular uptake, guiding the design of next-generation delivery vehicles.",
    status: "Active",
    focus: "Cellular Delivery",
    tags: ["Drug Delivery", "Computational Modeling", "Nanoparticle Design"],
    year: "2025 — Present",
  },
];

export const statistics = [
  { value: 12.8, suffix: "M+", label: "Biological measurements analyzed", prefix: "" },
  { value: 4.6, suffix: "B", label: "Cell-level observations", prefix: "" },
  { value: 27, suffix: "", label: "Research validation models", prefix: "" },
  { value: 93, suffix: "%", label: "Signal classification accuracy", prefix: "" },
];

export const biologicalScale = [
  {
    level: "Molecule",
    description: "Individual proteins, nucleic acids, and metabolites — the fundamental units of biological information.",
    detail: "We profile molecular interactions at nanometer resolution.",
  },
  {
    level: "Cell",
    description: "The basic functional unit of life — where molecular signals integrate into cellular behavior.",
    detail: "Single-cell analysis reveals heterogeneity hidden in bulk measurements.",
  },
  {
    level: "Tissue",
    description: "Organized cellular communities where spatial context shapes biological function.",
    detail: "Spatial profiling preserves the architecture that drives tissue behavior.",
  },
  {
    level: "System",
    description: "Interconnected organs and pathways that maintain organism-level homeostasis.",
    detail: "Systems-level understanding connects local biology to organism outcomes.",
  },
  {
    level: "Patient",
    description: "Every patient carries a unique biological story written in molecules, cells, and tissues.",
    detail: "Precision medicine begins with understanding individual biological variation.",
  },
];
